spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/nile0117
    username: root
    password: 1234
  jpa:
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update